version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install Firebase CLI
          command: npm install firebase-tools --save-dev
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build the Project
          command: |
            export CI=false
            npm run build
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token $FIREBASE_AUTH_TOKEN

workflows:
  version: 2
  deploy-on-push:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master  # Adjust to your deployment branch
